#!/usr/bin/env bash

################################################################################
#                                                                              #
# GIT ALIASES                                                                  #
#                                                                              #
################################################################################
# `cd` to git repo root
alias gr='git rev-parse 2>/dev/null && cd "./$(git rev-parse --show-cdup)"'
# `git clone` && `cd` to a repo directory
alias gitclone='source git-clone'
# delete local branches
alias gitdelete='git branch | egrep -v "(master|staging|develop|\*)" | xargs git branch -D'
# gist-file filename.ext  - create private gist from a file
alias gist-file='gist --private --copy'
# gist-paste filename.ext - create private gist from the clipboard contents
alias gist-paste='gist --private --copy --paste --filename'
