#!/usr/bin/env bash

################################################################################
#                                                                              #
# NODE ALIASES                                                                 #
#                                                                              #
################################################################################

##################################################
# NPM                                            #
##################################################
# default npm install
alias np="npm";

# install packages from package.json
alias npi="npm i";
# install local package dependency
alias npis="npm i --save";
# install local package devDependency
alias npid="npm i --save-dev";
# install global package
alias npig="npm i -g";

# list local packages
alias npl="npm ls --depth=0";
# list global packages
alias nplg="npm ls -g --depth=0";

# search packages
alias nps="npm search";

# test packages
alias npt="npm t";

# update local packages
alias npu="npm up";
# update global packages
alias npug="npm up -g";

# uninstall local packages
alias npun="npm un";
# uninstall global packages
alias npung="npm un -g";


##################################################
# YARN                                           #
##################################################
# default yarn install
alias yar="yarn";

# add local package dependency
alias yarna="yarn add";
# add local package devDependency
alias yarnad="yarn add -D";
# add local package peer dependency
alias yarnap="yarn add -P";
# add global package
alias yarnag="yarn global add";
# install packages from package.json
alias yarni="yarn install";

# list local packages
alias yarnl="yarn list --depth=0";
# list global packages
alias yarnlg="yarn global list --depth=0";

# remove local package
alias yarnr="yarn remove";
# remove global package
alias yarnrg="yarn global remove";

# search packages
alias yarns="yarn search";

# test packages
alias yarnt="yarn test";

# upgrade local packages
alias yarnu="yarn upgrade";
# interfactively upgrade local packages
alias yarnui="yarn upgrade-interactive";
# interfactively upgrade global packages
alias yarnuig="yarn global upgrade-interactive";
