#!/bin/sh
# Run by Strap after installing Brewfile dependencies

cd "$(dirname "$0")"/.. || exit

script/extract-onepassword-secrets
# script/install-vscode-extensions

if [ "$SHELL" != "/bin/zsh" ]
then
  chsh -s /usr/local/bin/zsh bruce
fi
