# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

name: 'Trigger: Push action'

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update Homebrew
      run: brew update

    - name: Install ShellCheck
      run:  brew install shellcheck

    - name: Run ShellCheck on these files
      run:  sh zsh/*.zsh shellscripts/*.sh install/*.sh
